##### PREFIX #####
unbind C-b
set -g prefix C-a
bind C-a send-prefix

##### INDEXING #####
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

##### SPLITS #####
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

##### SMART NVIM + TMUX NAVIGATION #####

# vim-tmux-navigator
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

##### RESIZE (Shift + HJKL) #####
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

##### WINDOWS #####
bind c new-window
bind n next-window
bind p previous-window

##### SESSIONS #####
bind s choose-tree -s

##### QUALITY OF LIFE #####
set -g mouse on
setw -g mode-keys vi

##### RELOAD #####
bind r source-file ~/.tmux.conf \; display-message "tmux reloaded"
